### ISSUE TITLE
tagtest command throwing Newtonsoft json reader exception

### ISSUE THREAD

**Issue by SebastianSchuetze** [microsoft/ApplicationInspector#102]
**Describe the bug**
I wanted to use the tagtest feature against a custom rule set. I took one rule from the default rule set into my own file to test this against an application.

analyze seems to work against my project

**To Reproduce**
1. Use the command in PowerShell 5.1.18362.145
```cmd
.\AppInspector.exe tagtest -s $projectDir -r "C:\temp\\myrules\one_custom_rule.json" --log-file-path $logDir --log-file-level Info  --console-verbosity high
```
2. run it against any project
3. See error
the following logs I got:
```Log
2020-01-24T13:43:32 1 INFO - [1/24/2020 2:43:32 PM] //////////////////////////////////////////////////////////
2020-01-24T13:43:32 1 INFO - Rule added: AI000700,Cloud Service: Hosting (Microsoft Azure),Cloud Service: Hosting (Microsoft Azure)
2020-01-24T13:43:32 1 INFO - Rule added: AI000700,Cloud Service: Hosting (Microsoft Azure),Cloud Service: Hosting (Microsoft Azure)
2020-01-24T13:43:32 1 WARN - no support for compressed type: .targets
2020-01-24T13:43:32 1 WARN - no support for compressed type: .targets
2020-01-24T13:43:32 1 WARN - no support for compressed type: .targets
2020-01-24T13:43:32 1 WARN - no support for compressed type: .targets
2020-01-24T13:43:32 1 ERROR - A runtime error has occured.  Please see log file for more information.
2020-01-24T13:43:32 1 ERROR - Runtime error: Unexpected character encountered while parsing value: M. Path '', line 0, position 0.    at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.AppInspector.TagTestCommand.Run()
   at Microsoft.AppInspector.Program.RunTagTestCommand(TagTestCommandOptions opts)
   at Microsoft.AppInspector.Program.<>c.<Main>b__6_2(TagTestCommandOptions opts)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 notParsedFunc)
   at Microsoft.AppInspector.Program.Main(String[] args)

```

**Expected behavior**
That I see a positive or negative answer if the feature is included in my solution or not.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 18363.592

**Additional context**
The file _one_custom_rule.json_ contains the following JSON

```json
[
  {
    "name": "Cloud Service: Hosting (Microsoft Azure)",
    "id": "AI000700",
    "description": "Cloud Service: Hosting (Microsoft Azure)",
    "tags": [
      "Metadata.CloudServices.Hosting.Microsoft.Azure"
    ],
    "severity": "moderate",
    "patterns": [
      {
        "pattern": "azure",
        "type": "string",
        "scopes": [ "code" ],
        "modifiers": [ "i" ],
        "confidence": "high"
      }
    ]
  } 
]
```

**Comment by guyacosta** [comment]
Fixed in build Release v1.0.23 and updated in the latest master code base.  The issue was reported in #97 and was related to a minor structural change in the json output from the analysis command that was not addressed in the TagTest and TagDiff commands.  The custom rule was not the issue.  Thanks for testing the feature and let us know of any further issues.
