### ISSUE TITLE
tagdiff error

### ISSUE THREAD

**Issue by yearnwang** [microsoft/ApplicationInspector#139]
**Describe the bug**
I want report for tagdiff,but I can't get report. 
show： A runtime error has occured.  Please see log file for more information.

**To Reproduce**
dotnet AppInspector.dll tagdiff --src1 7z-16.00.zip --src2 7z-19.00.zip

**Expected behavior**
log.txt
   at Microsoft.AppInspector.TagDiffCommand.Run()
   at Microsoft.AppInspector.Program.RunTagDiffCommand(TagDiffCommandOptions opts)
   at Microsoft.AppInspector.Program.<>c.<Main>b__6_1(TagDiffCommandOptions opts)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 notParsedFunc)
   at Microsoft.AppInspector.Program.Main(String[] args)

**Screenshots**
<img width="726" alt="tagdiff_error" src="https://user-images.githubusercontent.com/5487767/74638620-3479b080-51a7-11ea-95cb-254b8e0c2919.png">

**Desktop (please complete the following information):**
 - OS: win10_x64
 - Browser chorme
 - Version : 1.0.26

**Comment by guyacosta** [comment]
Thanks for reporting.  A recent change in how exclusion filters work in analyze command required the additional parameter be included as a required parameter for TagDiff and TagTest.  These are corrected but in addition the Analyze command will check first if a value was submitted before attempting a string operation.  Fixed in #140
