### ISSUE TITLE
The analysis process getting stuck at 50%

### ISSUE THREAD

**Issue by tanmayghosh2507** [microsoft/ApplicationInspector#200]
**Describe the bug**
I am running the App Inspector Analysis on a large repository with multiple languages, frameworks and components. The process runs fine till 50% but then it freezes there forever. And also, the appinspector.log.txt file is empty, hence have no idea what is going wrong.
I tried with some moderate or small sized repository, and it works fine.

**To Reproduce**
1. Clone a significantly large repository
2. Run `ApplicationInspector.CLI.exe analyze -s <Repo Local Path>`

**Expected behavior**
Firstly, the analysis should be complete. If not, then some error should be posted on command line where I am running the same, or logs should be written.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge Chromium

**Comment by guyacosta** [comment]
Sorry to see you're having issues.  Can you tell me the size of the repository you are scanning and is it a public one that I can download to investigate with?

**Comment by tanmayghosh2507** [comment]
The size of the repository is 839 MB. And sorry, the repository is not a public one, so can't share it here. Let me know if you need any other information about the repo.

**Comment by guyacosta** [comment]
How about the types of files in the project languages and whether the directory is zipped or contains any zipped or zipped within zipped files.  That might help.  Finally, what's the memory footprint look like when it hangs.

**Comment by scovetta** [comment]
For me, it aborts at 49% running against the Linux kernel, with this message in the log:

```
2020-05-04 13:45:11 1 ERROR - AppInsLog - Access to the path 'D:\ReferenceSource\linux\scripts\dtc\include-prefixes\arc' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.ReadAllBytes(String path)
   at MultiExtractor.MiniMagic.DetectFileType(String filename)
   at Microsoft.ApplicationInspector.Commands.AnalyzeCommand.GetResult()
2020-05-04 13:45:11 1 ERROR - AppInsLog - Unable to determine file type.  File open error for D:\ReferenceSource\linux\scripts\dtc\include-prefixes\arc
   at Microsoft.ApplicationInspector.Commands.AnalyzeCommand.GetResult()
   at Microsoft.ApplicationInspector.CLI.Program.RunAnalyzeCommand(CLIAnalyzeCmdOptions cliOptions)
   at Microsoft.ApplicationInspector.CLI.Program.VerifyOutputArgsRun(CLIAnalyzeCmdOptions options)
   at Microsoft.ApplicationInspector.CLI.Program.<>c.<Main>b__0_0(CLIAnalyzeCmdOptions cliOptions)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 notParsedFunc)
   at Microsoft.ApplicationInspector.CLI.Program.Main(String[] args)
```

I was able to cause a similar error using MultiExtract with OSS Gadget. I'll work on a fix there and we can port over here.

**Comment by guyacosta** [comment]
Sweet!  Thanks for investigating.  @tanmayghosh2507 this module is a shared one that scovetta owns.  Stand by we may have a solution for you very soon.

**Comment by tanmayghosh2507** [comment]
Thanks @guyacosta and @scovetta for looking into this.
Quick Update: I tried to run the same with the additional verb "-h first", and then the analysis was complete, though it took around 10 minutes. Thought of letting you know in case it helps!

**Comment by guyacosta** [comment]
That would seem to suggest it is not related to unzipping content.  Thanks that's a good data point.  I'll start investigating that aspect now as well as the #200.

**Comment by guyacosta** [comment]
Two issues were contributing here one the code had java lib zips which were very large also and getting unpacked and scanned but more interestingly one rule pattern in acl.json was returning tens of thousands of matches due to a pattern error "||".  To prevent similar issues for future rules and improve performance, a max matches per file is now set and the exclude default filter was updated to add "lib" as a folder that should not be scanned.

**Comment by scovetta** [comment]
Re-opening, failing similarly:

```
2020-05-06 14:33:46 1 ERROR - AppInsLog - Access to the path 'D:\ReferenceSource\linux\scripts\dtc\include-prefixes\arc' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.ReadAllBytes(String path)
   at MultiExtractor.MiniMagic.DetectFileType(String filename)
   at Microsoft.ApplicationInspector.Commands.AnalyzeCommand.GetResult()
2020-05-06 14:33:46 1 ERROR - AppInsLog - Unable to determine file type.  File open error for D:\ReferenceSource\linux\scripts\dtc\include-prefixes\arc
   at Microsoft.ApplicationInspector.Commands.AnalyzeCommand.GetResult()
   at Microsoft.ApplicationInspector.CLI.Program.RunAnalyzeCommand(CLIAnalyzeCmdOptions cliOptions)
   at Microsoft.ApplicationInspector.CLI.Program.VerifyOutputArgsRun(CLIAnalyzeCmdOptions options)
   at Microsoft.ApplicationInspector.CLI.Program.<>c.<Main>b__0_0(CLIAnalyzeCmdOptions cliOptions)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 notParsedFunc)
   at Microsoft.ApplicationInspector.CLI.Program.Main(String[] args)
```

I'd suggest cloning the Linux kernel and testing against that.

**Comment by guyacosta** [comment]
Will do.  I think this is a different issue than the one reported bytanmayghosh2507 and verified fixed using his codebase in both zipped and unzipped format.  I'll investigate the problem seen here by @scovetta in any case on this issue instance.

**Comment by guyacosta** [comment]
It's failing for files that have a zero length during the archive type check.  I have a fix in place that is being tested now.
