### ISSUE TITLE
Fails to write output

### ISSUE THREAD

**Issue by LordBenjamin** [microsoft/ApplicationInspector#71]
**Describe the bug**
```
2020-01-17T15:50:19 1 ERROR - A runtime error has occured.  Please see log file for more information.
2020-01-17T15:50:19 1 ERROR - Runtime error:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.AppInspector.LiquidWriter.WriteApp(AppProfile app)
   at Microsoft.AppInspector.AnalyzeCommand.FlushAll()
   at Microsoft.AppInspector.AnalyzeCommand.Run()
   at Microsoft.AppInspector.Program.RunAnalyzeCommand(AnalyzeCommandOptions opts)
   at Microsoft.AppInspector.Program.<>c.<Main>b__6_0(AnalyzeCommandOptions opts)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 notParsedFunc)
   at Microsoft.AppInspector.Program.Main(String[] args)
```

**To Reproduce**
1. Run the tool on any directory containing C# source code (`analyze -s .`)
2. Receive `A runtime error has occured.  Please see log file for more information.`
3. Check log file - always same stack trace

**Expected behavior**
Output file generated successfully.

**Desktop (please complete the following information):**
 - OS: Windows 10 (1809)

Also tried running with elevated privilege. Same result.

**Comment by guyacosta** [comment]
Can you verify you provided a file to run as the argument for -s i.e. -s [path].  It doesn't automatically use the existing directory as the assumed source path.

**Comment by LordBenjamin** [comment]
I used `-s ` to process the current working directory.

The tool spends time processing and fails after reaching 100% (or 2760% in one case!)
