### ISSUE TITLE
Failed to analyze with exception.  Possible zip file related issue for some cases.

### ISSUE THREAD

**Issue by CaoFeng1226** [microsoft/ApplicationInspector#74]
**Describe the bug**
Failed to write the result to a specified floder using "-o" arguements. 
Please check out the pics 

**To Reproduce**

**Expected behavior**
write the result to anywhere I specified. 

**Screenshots**
![image](https://user-images.githubusercontent.com/43327788/72692844-164d7000-3b69-11ea-9fa1-d37c5f3a3c89.png)

![image](https://user-images.githubusercontent.com/43327788/72692847-1c435100-3b69-11ea-9e2b-294c21db87c3.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [win 10 18363.592, ]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by guyacosta** [comment]
In the filepath is AIreport a folder or intended file name?  The value should end with a filename and difficult to tell from image.  Can you run with -v DEBUG and attach the log file.

**Comment by fadyosman** [comment]
I am having the same issue here, I tried both the pre-built binaries and I also compiled one from source, I got the following stack trace.

```
2020-01-22T20:49:06 1 ERROR - A runtime error has occured.  Please see log file for more information.
2020-01-22T20:49:06 1 ERROR - Runtime error: Wrong Central Directory signature    at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(FileStream file, Boolean leaveOpen)
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(FileStream file)
   at Microsoft.AppInspector.AnalyzeCommand.ProcessZipFile(String filename) in /media/fady/Data/Work/Programs/ApplicationInspector/AppInspector/Commands/AnalyzeCommand.cs:line 680
   at Microsoft.AppInspector.AnalyzeCommand.UnZipAndProcess(String filename) in /media/fady/Data/Work/Programs/ApplicationInspector/AppInspector/Commands/AnalyzeCommand.cs:line 650
   at Microsoft.AppInspector.AnalyzeCommand.Run() in /media/fady/Data/Work/Programs/ApplicationInspector/AppInspector/Commands/AnalyzeCommand.cs:line 275
   at Microsoft.AppInspector.Program.RunAnalyzeCommand(AnalyzeCommandOptions opts) in /media/fady/Data/Work/Programs/ApplicationInspector/AppInspector/Program.cs:line 269
   at Microsoft.AppInspector.Program.<>c.<Main>b__6_0(AnalyzeCommandOptions opts) in /media/fady/Data/Work/Programs/ApplicationInspector/AppInspector/Program.cs:line 230
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 notParsedFunc)
   at Microsoft.AppInspector.Program.Main(String[] args) in /media/fady/Data/Work/Programs/ApplicationInspector/AppInspector/Program.cs:line 224

```

The following is my .net information
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.10
 OS Platform: Linux
 RID:         ubuntu.19.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by guyacosta** [comment]
Helpful thanks.  It isn't clear whether it is the same issue first reported however there does seem to be an occasional issue related to uncompressing a package that I looked into earlier with the 3rd party component sharpziplib and I'm looking into replacing it.  For now, please attempt to unzip the file outside of the tool and try again.

**Comment by guyacosta** [comment]
Changing the title as it is not related to the -o argument but the analysis process itself and from the last user submitted input may be directly related to unzipping using a library.  See #81

**Comment by guyacosta** [comment]
Improves this issue replacing decompression code to extend supported formats and change approach.  Still dependent on sharpziplib and sharpcompressed now but with better results.  Note some file formats do not support forward reading or may encounter rar file signature issues as per these component projects due to complexity and support for the variations in structure etc.
