### ISSUE TITLE
Error running analyze command

### ISSUE THREAD

**Issue by pharindoko** [microsoft/ApplicationInspector#82]
**Describe the bug**
Trying to run the analyze command I get an error at the end of the process.

**To Reproduce**
executed command 
```
dotnet AppInspector.dll analyze -s [path] -l ff.log
```

at the end of the process this error occurs:

```
2020-01-20T21:03:37 1 ERROR - A runtime error has occured.  Please see log file for more information.
2020-01-20T21:03:37 1 ERROR - Runtime error: Unexpected EOF    at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Fill()
   at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at ICSharpCode.SharpZipLib.GZip.GZipInputStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at ICSharpCode.SharpZipLib.Tar.TarBuffer.ReadRecord()
   at ICSharpCode.SharpZipLib.Tar.TarBuffer.ReadBlock()
   at ICSharpCode.SharpZipLib.Tar.TarInputStream.GetNextEntry()
   at Microsoft.AppInspector.AnalyzeCommand.GetTarGzFileCount(String filename)
   at Microsoft.AppInspector.AnalyzeCommand.ProcessTarGzFile(String filename)
   at Microsoft.AppInspector.AnalyzeCommand.UnZipAndProcess(String filename)
   at Microsoft.AppInspector.AnalyzeCommand.Run()
   at Microsoft.AppInspector.Program.RunAnalyzeCommand(AnalyzeCommandOptions opts)
   at Microsoft.AppInspector.Program.<>c.<Main>b__6_0(AnalyzeCommandOptions opts)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 notParsedFunc)
   at Microsoft.AppInspector.Program.Main(String[] args)

```
**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Macos Mojave

**Comment by pharindoko** [comment]
#71

**Comment by guyacosta** [comment]
It looks like the zip file is corrupt.  Try unzipping outside of Application Inspector first and if the file is not at fault or debugging through which file in your zip is at fault.  If the zip file is on a public repo include the URL after verifying it is able to unzip using a standard tool.

**Comment by pharindoko** [comment]
> It looks like the zip file is corrupt. Try unzipping outside of Application Inspector first and if the file is not at fault or debugging through which file in your zip is at fault. If the zip file is on a public repo include the URL after verifying it is able to unzip using a standard tool.

Hi,

sorry I don`t get it.
I downloaded and extracted the appinspector 
used it with a path:
```
 dotnet AppInspector.dll analyze -s ../bla/bla/ -l ff.log
````

What does the Sharpziplib at the end of the process.
No zip file was created.
Anyways,  I would expect to get an html file as output...
